// Auth
export const EMAIL_CHANGE = 'EMAIL_CHANGE'
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

// Employee handling
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS'
export const EMPLOYEE_SAVE_SUCCESS = 'EMPLOYEE_SAVE_SUCCESS'